/**
 * interfaces.ts
 *
 * TNA (Text Network Analysis) domain types.
 *
 * These types form the foundation for the entire TNA pipeline:
 *   - TextNode: a canonical concept node (ID = lemma form)
 *   - TextEdge: a weighted co-occurrence edge from 4-gram sliding window
 *   - GapMetrics: inter-community structural gap measurements
 *   - CommunityAssignment: Louvain community detection output
 *   - TNAConfig: configuration with defaults
 *   - PreprocessResult: output of the TF-IDF + lemmatization pipeline
 *
 * ZERO external imports — pure TypeScript interfaces only.
 */

// ---------------------------------------------------------------------------
// Branded ID type
// ---------------------------------------------------------------------------

/**
 * TextNodeId — opaque branded string type for TNA graph node IDs.
 *
 * The ID IS the canonical lemma form of the concept. For example, the
 * surface forms "running", "runs", "ran" all map to TextNodeId "run".
 *
 * Matches the VertexId/EdgeId pattern from GraphTypes.ts for consistency.
 */
export type TextNodeId = string & { readonly __brand: "TextNodeId" };

// ---------------------------------------------------------------------------
// Core graph types
// ---------------------------------------------------------------------------

/**
 * TextNode — a node in the TNA co-occurrence graph.
 *
 * Represents a unique semantic concept identified by its canonical lemma.
 * The node tracks all morphological surface forms observed across ingested text.
 *
 * Design invariant: `id` is always a TextNodeId (branded canonical lemma).
 * No raw surface forms appear as node IDs — lemmatization happens BEFORE
 * graph insertion.
 */
export interface TextNode {
  readonly id: TextNodeId;
  /** Canonical lemma form (same as id.valueOf(), but typed as string for convenience). */
  readonly lemma: string;
  /** All morphological variants observed in source text (e.g., "running", "runs", "ran"). */
  readonly surfaceForms: readonly string[];
  /** TF-IDF weight for this concept in the source corpus. */
  readonly tfidfWeight: number;
  /** Community label assigned by LouvainDetector. Set after community detection. */
  readonly communityId?: number;
  /** Betweenness centrality score. Set after CentralityAnalyzer runs. */
  readonly betweennessCentrality?: number;
  /** Horizontal layout position (set after LayoutComputer runs). */
  readonly x?: number;
  /** Vertical layout position (set after LayoutComputer runs). */
  readonly y?: number;
}

/**
 * TextEdge — a weighted co-occurrence edge in the TNA graph.
 *
 * Weight reflects co-occurrence proximity in the 4-gram sliding window:
 *   - adjacency distance 1: weight += 3
 *   - adjacency distance 2: weight += 2
 *   - adjacency distance 3: weight += 1
 *
 * `createdAtIteration` supports Phase 4 SOC per-iteration surprising-edge-ratio
 * computation (prevents Pitfall 9: surprising edge ratio as cumulative measure).
 */
export interface TextEdge {
  readonly source: TextNodeId;
  readonly target: TextNodeId;
  /** Accumulated co-occurrence weight from all 4-gram window occurrences. */
  readonly weight: number;
  /**
   * Reasoning iteration at which this edge was first created.
   * Required for Phase 4 SOC per-iteration surprising-edge-ratio.
   * Prevents Pitfall 9: treating surprising-edge-ratio as cumulative.
   */
  readonly createdAtIteration: number;
}

// ---------------------------------------------------------------------------
// Community analysis types
// ---------------------------------------------------------------------------

/**
 * CommunityAssignment — result of Louvain community detection for a single node.
 */
export interface CommunityAssignment {
  readonly nodeId: TextNodeId;
  readonly communityId: number;
  readonly modularity: number;
}

/**
 * GapMetrics — structural gap measurements between two communities.
 *
 * Used to detect semantic gaps for Molecular-CoT bridging operations.
 * Phase 3 TNA-04 (GapDetector) produces these from the co-occurrence graph.
 */
export interface GapMetrics {
  readonly communityA: number;
  readonly communityB: number;
  /** Density of edges crossing the boundary between communities A and B. */
  readonly interCommunityDensity: number;
  /** Shortest path length between any node in A and any node in B. */
  readonly shortestPathLength: number;
  /**
   * Change in modularity if the gap were bridged.
   * Negative = bridging would reduce modularity (structural gap is real).
   */
  readonly modularityDelta: number;
  /** Nodes that lie on shortest paths between communities (bridge candidates). */
  readonly bridgeNodes: readonly TextNodeId[];
}

// ---------------------------------------------------------------------------
// Phase 6: Catalyst question types (TNA-07)
// ---------------------------------------------------------------------------

/**
 * CatalystQuestion — a targeted question designed to bridge two communities.
 *
 * Generated by CatalystQuestionGenerator for each structural gap.
 * Used as reasoning priors for VdW agents (ORCH-06).
 */
export interface CatalystQuestion {
  /** The structural gap this question targets. */
  readonly gapId: string;

  /** Community IDs being bridged. */
  readonly communityA: number;
  readonly communityB: number;

  /** The generated question text. */
  readonly questionText: string;

  /** Representative nodes from each community used as seed concepts. */
  readonly seedNodeA: string;
  readonly seedNodeB: string;

  /** Semantic distance between communities (0-1; 1 = maximum void). */
  readonly semanticDistance: number;

  /** Priority ranking (lower = higher priority). */
  readonly priority: number;
}

// ---------------------------------------------------------------------------
// Phase 6: Centrality time-series types (TNA-09)
// ---------------------------------------------------------------------------

/**
 * CentralityTrend — direction of centrality change over time.
 */
export type CentralityTrend = "rising" | "falling" | "stable" | "oscillating";

/**
 * CentralityTimeSeries — time-series centrality data for a single node.
 */
export interface CentralityTimeSeries {
  readonly nodeId: string;
  readonly scores: ReadonlyArray<{ iteration: number; score: number }>;
  readonly trend: CentralityTrend;
  readonly peak: { iteration: number; score: number } | null;
  readonly valley: { iteration: number; score: number } | null;
}

/**
 * CentralityTimeSeriesConfig — configuration for time-series tracking.
 */
export interface CentralityTimeSeriesConfig {
  /**
   * Default interval (iterations) between centrality recomputations.
   * Default: 10
   */
  readonly defaultComputeInterval: number;

  /**
   * Interval during transitioning/critical regimes.
   * Default: 5
   */
  readonly urgentComputeInterval: number;

  /**
   * Interval during stable regimes.
   * Default: 20
   */
  readonly relaxedComputeInterval: number;

  /**
   * Minimum trend slope magnitude to classify as rising/falling.
   * Default: 0.05
   */
  readonly trendSlopeThreshold: number;

  /**
   * Multiplier for rapid centrality change detection.
   * If score increases by this factor in 2 data points, emit event.
   * Default: 3.0 (3x increase)
   */
  readonly rapidChangeMultiplier: number;
}

// ---------------------------------------------------------------------------
// Phase 6: Layout types (TNA-08)
// ---------------------------------------------------------------------------

/**
 * NodePosition — 2D coordinates for a graph node computed by LayoutComputer.
 *
 * Positions are in an arbitrary coordinate space defined by the ForceAtlas2
 * physics simulation. They are meaningful only relative to each other:
 * closer nodes have stronger co-occurrence relationships.
 */
export interface NodePosition {
  readonly x: number;
  readonly y: number;
}

/**
 * LayoutConfig — physics simulation parameters for the ForceAtlas2 algorithm.
 *
 * All parameters have documented defaults that produce good visualizations
 * for TNA co-occurrence graphs (sparse, community-structured graphs).
 */
export interface LayoutConfig {
  /** Number of simulation iterations. Default: 100 */
  readonly iterations: number;

  /** Use Barnes-Hut optimization for O(n log n) repulsion. Default: true */
  readonly barnesHutOptimize: boolean;

  /** Barnes-Hut accuracy parameter (0.5 = balanced accuracy/speed). Default: 0.5 */
  readonly barnesHutTheta: number;

  /** LinLog mode (logarithmic attraction — better for sparse graphs). Default: false */
  readonly linLogMode: boolean;

  /** Gravity constant (pulls nodes toward center). Default: 1.0 */
  readonly gravity: number;

  /** Slowdown factor (larger = more stable but slower). Default: 1.0 */
  readonly slowDown: number;

  /** Edge weight influence on attraction forces. Default: 1.0 */
  readonly edgeWeightInfluence: number;

  /** Scaling ratio (repulsion strength relative to node count). Default: 2.0 */
  readonly scalingRatio: number;

  /** Use strong gravity mode (non-linear gravity). Default: false */
  readonly strongGravityMode: boolean;

  /** Random seed for deterministic initial position assignment. Default: 42 */
  readonly seed: number;
}

/**
 * LayoutOutput — result of a single ForceAtlas2 layout computation.
 *
 * Energy is the convergence metric: sum of squared position deltas from
 * the previous layout, normalized by node count. Lower energy = more stable.
 */
export interface LayoutOutput {
  /** Map of nodeId → 2D position after ForceAtlas2 simulation. */
  readonly positions: ReadonlyMap<string, NodePosition>;

  /**
   * Convergence energy: mean squared displacement from previous layout.
   * First computation returns Infinity (no previous reference).
   * Below ~1.0 indicates the layout has largely converged.
   */
  readonly energy: number;

  /** Number of ForceAtlas2 physics iterations executed in this run. */
  readonly iterations: number;

  /** Number of nodes positioned in this layout. */
  readonly nodeCount: number;

  /** Number of edges in the graph at layout time. */
  readonly edgeCount: number;
}

/**
 * LayoutExportJSON — JSON-serializable layout for visualization consumers.
 *
 * Compatible with D3.js force simulation and Sigma.js graph renderers.
 * Contains all information needed to render the semantic graph visually.
 */
export interface LayoutExportJSON {
  readonly nodes: ReadonlyArray<{
    /** Node identifier (canonical lemma). */
    readonly id: string;
    /** Horizontal layout position. */
    readonly x: number;
    /** Vertical layout position. */
    readonly y: number;
    /** Community cluster ID (from Louvain). */
    readonly communityId?: number;
    /** Betweenness centrality score [0, 1]. */
    readonly betweennessCentrality?: number;
    /** Human-readable label (same as id for TNA nodes). */
    readonly label: string;
  }>;
  readonly edges: ReadonlyArray<{
    /** Source node ID. */
    readonly source: string;
    /** Target node ID. */
    readonly target: string;
    /** Accumulated co-occurrence weight. */
    readonly weight: number;
  }>;
  readonly metadata: {
    /** Number of nodes in this layout. */
    readonly nodeCount: number;
    /** Number of edges in this layout. */
    readonly edgeCount: number;
    /** Convergence energy (lower = more settled). */
    readonly energy: number;
    /** Physics iterations executed. */
    readonly iterations: number;
    /** Unix timestamp (ms) at layout export time. */
    readonly timestamp: number;
  };
}

/**
 * LayoutComputerConfig — configuration for automatic layout scheduling.
 *
 * Controls when layouts are recomputed (interval) and how convergence
 * is assessed. Regime-adaptive: critical/transitioning = more frequent.
 */
export interface LayoutComputerConfig {
  /** Default interval (reasoning iterations) between layout computations. Default: 15 */
  readonly defaultComputeInterval: number;

  /** Interval during transitioning/critical regimes (more frequent). Default: 10 */
  readonly urgentComputeInterval: number;

  /** Interval during stable regimes (less frequent). Default: 20 */
  readonly relaxedComputeInterval: number;

  /**
   * Energy threshold below which layout is considered converged.
   * isConverged() returns true when energy < this value. Default: 1.0
   */
  readonly convergenceEnergyThreshold: number;

  /** Minimum graph node count to run layout (trivial for smaller). Default: 3 */
  readonly minGraphOrder: number;

  /**
   * Iteration multiplier for incremental updates (after initial full layout).
   * Incremental iterations = round(full_iterations * multiplier). Default: 0.5
   */
  readonly incrementalMultiplier: number;
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/**
 * TNAConfig — configuration for the TNA pipeline with documented defaults.
 *
 * All fields optional; Preprocessor and CooccurrenceGraph apply defaults.
 */
export interface TNAConfig {
  /**
   * Number of tokens in each sliding window (default: 4).
   * A 4-gram window creates edges with weights 3, 2, 1 for distances 1, 2, 3.
   */
  windowSize?: number;
  /**
   * Minimum TF-IDF weight for a token to be included in output (default: 0.1).
   * Tokens below this threshold are treated as stop-like and dropped.
   */
  minTfidfWeight?: number;
  /**
   * Random seed for Louvain community detection (default: 42).
   * Fixed seed ensures deterministic community assignments.
   */
  louvainSeed?: number;
  /**
   * Language code for stopword removal (default: 'en').
   * Passed to stopword library for language-specific stopword corpus.
   */
  language?: string;
}

// ---------------------------------------------------------------------------
// Preprocessing result
// ---------------------------------------------------------------------------

/**
 * PreprocessResult — output of the Preprocessor.preprocess() pipeline.
 *
 * `tokens` are guaranteed to be:
 *   1. Lowercased
 *   2. Stopword-removed
 *   3. Lemmatized (canonical form only — no surface forms appear here)
 *   4. TF-IDF filtered (below minTfidfWeight dropped)
 *
 * No raw surface forms ever appear in `tokens`. This is the primary
 * pitfall guard for TNA (Pitfall: 4-gram window without lemmatization).
 */
export interface PreprocessResult {
  /** Lemmatized, stopword-removed, TF-IDF-filtered tokens in order. */
  readonly tokens: readonly string[];
  /** TF-IDF score per lemma for this document within the current corpus. */
  readonly tfidfScores: ReadonlyMap<string, number>;
}

/**
 * DetailedPreprocessResult — PreprocessResult extended with surface form tracking.
 *
 * Used by CooccurrenceGraph to populate TextNode.surfaceForms — the full record
 * of which morphological variants (surface forms) were observed for each lemma.
 *
 * `surfaceToLemma` maps each original (post-stopword-removal) surface token to
 * its canonical lemma. For example: "running" → "run", "runs" → "run".
 */
export interface DetailedPreprocessResult extends PreprocessResult {
  /**
   * Maps each pre-lemmatization surface form to its canonical lemma.
   * Used to populate TextNode.surfaceForms for morphological variant tracking.
   */
  readonly surfaceToLemma: ReadonlyMap<string, string>;
}
